### ISSUE TITLE
thread 'main' panicked at 'cannot found the library WINSPOOL.DRV on maps32/', src/emu/pe32.rs:848:17

### ISSUE THREAD

**Issue by brandonros** [sha0coder/scemu#10]
```
thread 'main' panicked at 'cannot found the library WINSPOOL.DRV on maps32/', src/emu/pe32.rs:848:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: scemu::emu::pe32::PE32::iat_binding
   3: scemu::emu::Emu::load_pe32
   4: scemu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by brandonros** [comment]
```
Brandons-MacBook-Air:scemu brandonros 2022-09-07 00:33:04 $ ls -lh maps32/WINSPOOL.DRV 
-rw-r--r--  1 brandonros  staff   439K Sep  7 00:31 maps32/WINSPOOL.DRV
Brandons-MacBook-Air:scemu brandonros 2022-09-07 00:33:10 $ file maps32/WINSPOOL.DRV 
maps32/WINSPOOL.DRV: PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
```
