### ISSUE TITLE
not implemented: unimplemented register SPL

### ISSUE THREAD

**Issue by brandonros** [sha0coder/scemu#13]
```
thread 'main' panicked at 'not implemented: unimplemented register SPL', src/emu/regs64.rs:970:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: scemu::emu::regs64::Regs64::get_reg
   3: scemu::emu::Emu::get_operand_value
   4: scemu::emu::Emu::run
   5: scemu::emu::Emu::load_code
   6: scemu::main

```

just to track our latest progress

**Comment by brandonros** [comment]
https://www.tortall.net/projects/yasm/manual/html/arch-x86-registers.html

**Comment by brandonros** [comment]
looks like it is 8 bits from rsp? not sure

https://www.cs.uaf.edu/2017/fall/cs301/reference/x86_64.html

**Comment by brandonros** [comment]
done here https://github.com/sha0coder/scemu/commit/36c66f1145ce4cc83cffb3c3a8f0cbbcf87b055d
