### ISSUE TITLE
thread 'main' panicked at 'no import directory at va 0x0', src\emu\pe32.rs:634:13

### ISSUE THREAD

**Issue by icyfox168168** [sha0coder/scemu#4]
vs 2022 build 64bits exe

cargo build --release
    Finished release [optimized] target(s) in 0.08s

target\release\scemu.exe --64bits -f exe.exe
use -vv to see the assembly code emulated, and -v to see the messages
initializing regs
loading memory maps
memory test Ok.
PE32 header detected.
thread 'main' panicked at 'no import directory at va 0x0', src\emu\pe32.rs:634:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by icyfox168168** [comment]
#include <iostream>

int main()
{
    std::cout << "Hello World!\n";

    getchar();
}

stack backtrace:
   0:     0x7ff6b8ea383f - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff6b8ea383f - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff6b8ea383f - std::sys_common::backtrace::_print_fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff6b8ea383f - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff6b8ebaeea - core::fmt::write
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\fmt\mod.rs:1194
   5:     0x7ff6b8e9ded9 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\io\mod.rs:1655
   6:     0x7ff6b8ea5b2b - std::sys_common::backtrace::_print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff6b8ea5b2b - std::sys_common::backtrace::print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff6b8ea5b2b - std::panicking::default_hook::closure$1
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:295
   9:     0x7ff6b8ea571e - std::panicking::default_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:314
  10:     0x7ff6b8ea6121 - std::panicking::rust_panic_with_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:698
  11:     0x7ff6b8ea5fdd - std::panicking::begin_panic_handler::closure$0
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:588
  12:     0x7ff6b8ea4147 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:138
  13:     0x7ff6b8ea5cb9 - std::panicking::begin_panic_handler
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:584
  14:     0x7ff6b8ec57c5 - core::panicking::panic_fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:143
  15:     0x7ff6b8d6185e - scemu::emu::pe32::PE32::load::hdc4247c0225a569c
  16:     0x7ff6b8ce5578 - scemu::emu::Emu::load_pe32::h53cf23e5d9545099
  17:     0x7ff6b8ce6da6 - scemu::emu::Emu::load_code::he4d94360ce957268
  18:     0x7ff6b8d7cc0e - scemu::emu::exception::exit::h474f2d9f5ecda7ea
  19:     0x7ff6b8d87b06 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4c71251f77b9ed66
  20:     0x7ff6b8d7158c - std::io::buffered::bufwriter::BufWriter<W>::flush_buf::h4f9699b94cc10984
  21:     0x7ff6b8e977ae - core::ops::function::impls::impl$2::call_once
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\ops\function.rs:259
  22:     0x7ff6b8e977ae - std::panicking::try::do_call
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:492
  23:     0x7ff6b8e977ae - std::panicking::try
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:456
  24:     0x7ff6b8e977ae - std::panic::catch_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panic.rs:137
  25:     0x7ff6b8e977ae - std::rt::lang_start_internal::closure$2
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\rt.rs:128
  26:     0x7ff6b8e977ae - std::panicking::try::do_call
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:492
  27:     0x7ff6b8e977ae - std::panicking::try
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:456
  28:     0x7ff6b8e977ae - std::panic::catch_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panic.rs:137
  29:     0x7ff6b8e977ae - std::rt::lang_start_internal
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\rt.rs:128
  30:     0x7ff6b8d7df17 - main
  31:     0x7ff6b8ec13ec - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  32:     0x7ff6b8ec13ec - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  33:     0x7ffecc7a6fd4 - BaseThreadInitThunk
  34:     0x7ffeccb3cec1 - RtlUserThreadStart
