### ISSUE TITLE
thread 'main' panicked at 'not implemented: unimplemented register SIL', src/emu/regs64.rs:943:18

### ISSUE THREAD

**Issue by brandonros** [sha0coder/scemu#8]
```
RUST_BACKTRACE=1 cargo run --release -- -6 -f /Users/brandonros/Downloads/redacted.exe 
    Finished release [optimized] target(s) in 0.08s
     Running `target/release/scemu -6 -f /Users/brandonros/Downloads/redacted.exe`
use -vv to see the assembly code emulated, and -v to see the messages
initializing regs
loading memory maps
memory test Ok.
PE64 header detected.
no import directory at va 0xc4f.
IAT Bound started ...
IAT Bound.
Loaded /Users/brandonros/Downloads/redacted.exe
  11 sections  base addr 0x140000000
  created pe32 map for section `.text` at 0x140001000 size: 10524854
  entry point at 0x144901722  0x4901722 
  created pe32 map for section `.rdata` at 0x140a0b000 size: 32899160
  created pe32 map for section `.data` at 0x14296c000 size: 371428
  created pe32 map for section `.pdata` at 0x1429c7000 size: 232872
  created pe32 map for section `.qtmetad` at 0x142a00000 size: 1334
  created pe32 map for section `.qtmimed` at 0x142a01000 size: 322789
  created pe32 map for section `.tls` at 0x142a50000 size: 24
  created pe32 map for section `.jPc0` at 0x142a51000 size: 5392274
  created pe32 map for section `.jPc1` at 0x142f76000 size: 6456
  created pe32 map for section `.jPc2` at 0x142f78000 size: 34504780
/!\ warning: raw sz:34786304 off:34512896 sz:273408  off+sz:34786304
  created pe32 map for section `.rsrc` at 0x145061000 size: 273368
 ----- emulation -----
thread 'main' panicked at 'not implemented: unimplemented register SIL', src/emu/regs64.rs:943:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: scemu::emu::regs64::Regs64::get_reg
   3: scemu::emu::Emu::get_operand_value
   4: scemu::emu::Emu::run
   5: scemu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sha0coder** [comment]
I implemented support for SIL and DIL registers.

my email is: sha0 at badchecksum dot net
if you send me the binary i can do some tests and implement more stuff.

regards.

**Comment by brandonros** [comment]
emailed

closed by https://github.com/sha0coder/scemu/commit/0c350b674b4f68c566697ab58fbfc5d294b45119
